os: linux
dist: trusty
sudo: required
before_install:
- 'if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then return 1; fi'
- mkdir /home/travis/devkitPro
- cd /home/travis/devkitPro
- wget "https://3dsthem.es/app/devkitpro.tar.bz2"
- tar xf devkitpro.tar.bz2
- export DEVKITPRO=/home/travis/devkitPro
- export DEVKITARM=${DEVKITPRO}/devkitARM
- export PATH=$PATH:${DEVKITARM}/bin
- chmod +x $TRAVIS_BUILD_DIR/buildtools/3ds/*
install:
- cd $TRAVIS_BUILD_DIR
- wget --no-check-certificate https://raw.githubusercontent.com/libretro/RetroArch/master/ctr/tools/bannertool-linux
- chmod +x bannertool-linux
- sudo mv bannertool-linux buildtools/3ds/bannertool-linux64
- cd
script:
- cd $TRAVIS_BUILD_DIR
- sed -i "s/-DVERSION='\".*\"'/-DVERSION='\"$(echo $TRAVIS_COMMIT | cut -c -7)-git\"'/" Makefile
- make -j
after_success:
- 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then npm init -y; npm install github; node ./.travis-upload.js; fi'
addons:
  apt:
    packages:
    - libstdc++6
